### PR TITLE
Fix shading issue in iOS

### PR DESCRIPTION
**Pull request by dy**
Before
image
after
image

### CODE REVIEW

**Comment by dy** [comment]
@etpinard are we going to merge this?

**Comment by etpinard** [comment]
Has anyone tested this?

I don't have access to an iOS device. @dfcreative can you make a standalone plotly.js example with this patch in it?

**Comment by dy** [comment]
@etpinard
Example with bug https://dfcreative.github.io/plotly-contrib/gl-surface3d-bad.html
Example with fixed bug https://dfcreative.github.io/plotly-contrib/gl-surface3d-good.html

**Comment by etpinard** [comment]
Can someone with an iOS device test this?

cc @rreusser @monfera @alexcjohnson

**Comment by monfera** [comment]
@etpinard it looks fantastic with the `good` version! (iPhone 6)

**Comment by monfera** [comment]
Totally unrelated (probably scene related rather than `gl-surface3d`), just noticed this axis flashing on testing the above with camera rotation (independent of OS):

flash

**Comment by rreusser** [comment]
Beautiful! On iPhone 5.

**Comment by etpinard** [comment]
Great. Thanks for checking!

This will be part of plotly.js `1.29.0` (as I'm always a little afraid of including shader patches in patch releases).

**Comment by etpinard** [comment]
@dfcreative :dancer: can you merge and publish this and bump the plotly.js package.json?

**Pull request merged**
